a = [
      '3D Vision',
      'Audio/Speech',
      'Autonomous Driving',
      'Classification',
      'Computer Vision',
      'Dataset/Benchmark',
      'Detection',
      'Domain Adaptation',
      'Efficiency',
      'Embodied AI',
      'Few-Shot Learning',
      'General',
      'Generative Models',
      'Graph Learning',
      'Machine Learning',
      'Survey',
      'Self-Supervised',
      'RL',
      'Transformer',
      'Segmentation',
      'Tracking',
      'Face Recognition',
      'Pose Estimation',
      'Navigation',
      'Video Understanding',
      'Neural Rendering',
      'Medical Imaging',
      'Multimodality',
    ],

print(sorted(a))